name: Delivery

on:
  push:
    branches: [ master ]

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 0
    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.SERVER_ADDRESS }}
        user: ${{ secrets.SFTP_USER }}
        password: ${{ secrets.SFTP_PASSWORD }}
        remoteDir: ${{ secrets.SFTP_PATH }}
        
#                   host: ${{ secrets.SERVER_ADDRESS }}
#           user: ${{ secrets.SFTP_USER }}
#           password: ${{ secrets.SFTP_PASSWORD }}
#           #private_key: ${{ secrets.SSH_PRIVATE_KEY }}
#           remote_path: ${{ secrets.SFTP_PATH }}
#             ignore: .github/**,.gitignore,**/.gitignore,package.json,package-lock.json:  
