name: Delivery

on:
  push:
    branches: [ master ]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: deploy
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0      
      - name: deploy files
        uses:  swznd/sftp-deploy@master
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          user: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASSWORD }}
          #private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_path: ${{ secrets.SFTP_PATH }}
          ignore: .github/**,.gitignore,**/.gitignore,package.json,package-lock.json
