name: Delivery

on:
  push:
    branches: [ master ]

jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 0
    - name: Upload to FTP
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        host: ${{ secrets.SERVER_ADDRESS }}
        user: ${{ secrets.SFTP_USER }}
        password: ${{ secrets.SFTP_PASSWORD }}
